# Generated by Django 4.0 on 2021-12-18 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='lookup time')),
                ('hash_field', models.CharField(max_length=32)),
                ('data', models.BinaryField(max_length=32768)),
            ],
        ),
    ]
