# Generated by Django 4.0 on 2021-12-21 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPriceLTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_sell', models.DecimalField(decimal_places=8, max_digits=12)),
                ('best_buy', models.DecimalField(decimal_places=8, max_digits=12)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('volume_24', models.DecimalField(decimal_places=8, max_digits=14)),
                ('lookup_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='lookup time')),
                ('sell_change', models.IntegerField()),
                ('buy_change', models.IntegerField()),
                ('hash_field', models.CharField(max_length=32)),
                ('data', models.BinaryField(max_length=32768)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=14)),
                ('date', models.DateTimeField()),
                ('label', models.CharField(max_length=127)),
                ('order_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('total', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'abstract': False,
                'unique_together': {('amount', 'date', 'label', 'order_id', 'price', 'total')},
            },
        ),
        migrations.CreateModel(
            name='FaucetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ordersnapshot',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=14)),
                ('date', models.DateTimeField()),
                ('label', models.CharField(max_length=127)),
                ('order_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('total', models.DecimalField(decimal_places=8, max_digits=12)),
            ],
            options={
                'abstract': False,
                'unique_together': {('amount', 'date', 'label', 'order_id', 'price', 'total')},
            },
        ),
        migrations.CreateModel(
            name='OrderBookState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_time', models.DateTimeField(verbose_name='lookup time')),
                ('buy_orders', models.ManyToManyField(to='order_app.BuyOrder')),
                ('sell_orders', models.ManyToManyField(to='order_app.SellOrder')),
            ],
        ),
    ]
